version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/nodejs-aws-codedeploy-pipeline
hooks:
# ApplicationStop:
# DownloadBundle:
#  BeforeInstall:
# Install:
AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ec2-user@ip-172-31-18-96
ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user@ip-172-31-18-96
# ValidateService:
