version: 0.0
Resources:
  - myECSService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:us-east-1:713881791522:task-definition/nodejs-app-task:1
        LoadBalancerInfo:
          ContainerName: nodejs-container
          ContainerPort: 3000
