name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
permissions:
  contents: read
jobs:
  run-jest-tests:
    # Name of the job as it will be displayed in GitHub
    name: Jest Tests
    # Machine which this action will be run on. For a list of all the machines available/how to run on self hosted machine visit
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest

    # Steps this job must take to complete
    steps:
      # Reference the main branch. For more information visit https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      # Specify which version of Node this project is using. For more information visit.
      # https://docs.github.com/en/actions/guides/building-and-testing-nodejs#specifying-the-nodejs-version
      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.1

      - name: Install all dependencies
        run: npm install

      - name: Run Jest Tests
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1
    - name: Checkout to repo
      uses: actions/checkout@v2

      # Step 2
    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

      # Step 3
    - name: Create CodeDeploy Deployment
      id: deploy
      run: |
        aws deploy create-deployment \
        --application-name node-app-23 \
        --deployment-group-name node-app-23-DG \
        --deployment-config-name CodeDeployDefault.OneAtATime \
        --github-location repository=${{ github.repository }},commitId=${{ github.sha }}